import { Container } from '@mui/material'
import type { NextPage } from 'next'
import Head from 'next/head'
import Topbar from '../src/Topbar'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Topbar />
      <Container>
        <h1>Foo</h1>
        <h2>Bar</h2>
        <p>Baz</p>
      </Container>
    </>
  )
}

export default Home
