import { Container, Grid, Box, Card } from '@mui/material';
import type { NextPage } from 'next'
import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';
import Layout from '../src/Layout'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>SFJ - Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Grid container>
          <Grid item xs={8}>
            <main>
              <h1>About me</h1>

              <p>
                My name is Simon From Jakobsen, I am 18 years of age and love computers, especially programming.
                I was born, raised and still live in Viborg, Denmark, studying at Mercantec Viborg.
                I've been programming since I was 10 years of age, starting with Java and HTML.
                Nowadays I do all sort of <Link href="#">projects</Link> in all sorts of languages.
                I've been interested in technology my whole life, and have started taking it seriously in the recent years.
              </p>

              <h2>Occupation</h2>
                
              <p>
                I am currently enrolled in an EUX datatechnician education as a datatechnician apprentice.
                focusing on computer science and programming combined with a technical highschool education.
                EUX is a vocational and highschool education combined, spanning a bit longer, and switching every 6 month or so between the two. 
                When finished, I will have achieved the title of »datatechnician specialied in programming« and a danish highschool diploma.
                Time not spent studying is usually spent on either friends, programming or playing piano.
              </p>
            </main>
          </Grid>
          <Grid item xs={4} style={{padding: '1rem', marginTop: '4rem'}}>
            <Box style={{overflow: 'hidden', borderRadius: '1rem'}}>
              <Image src='/avatar.jpg' width={400} height={400} layout={'responsive'} />
            </Box>
          </Grid>
        </Grid>
      </Layout>
    </>
  )
}

export default Home
